[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
once_cell = "1.16.0"
priority-queue = "1.3.0"
num = "0.4.0"

[lib]
name = "lib"
path = "src/lib.rs"
