[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
num-traits = "0.2.19"
regex = "1.11.1"
strum = "0.26.3"
strum_macros = "0.26.4"

[lib]
name = "lib"
path = "src/lib.rs"
