const input = "bqlpzruexkszyahnamgjdctvfs\n" +
    "bqlporuexkwyyahnbmgjdctvfb\n" +
    "bqlhoruexkwzyahefmgjdctvfs\n" +
    "bqlporuegkwzyahdimgodctvfs\n" +
    "bqlporuxxkwhybhnimgjdctvfs\n" +
    "dqlporuexkwzyahnimgjfcivfs\n" +
    "bqlporlexkwzyarniigjdctvfs\n" +
    "bqlporuezkqzeahnimgjdctvfs\n" +
    "bqlporuefkwzyamnsmgjdctvfs\n" +
    "bqlporuexkwzyahqimgjdazvfs\n" +
    "bqspocuexkwzyahnimgjdctffs\n" +
    "bqlporuexkwzywhnimgjiccvfs\n" +
    "bqlcoruexkwzyahnimgjdgtvfj\n" +
    "bqljoruexkwvyahnimgcdctvfs\n" +
    "bqeporuexkwzyahnionjdctvfs\n" +
    "bqlporuexkwzyabnxmgjqctvfs\n" +
    "bqjporuexkwzyahnimtddctvfs\n" +
    "bqlprruexkezyahbimgjdctvfs\n" +
    "bqlporuexkazyahnimgjjctefs\n" +
    "bqlioruexkweyjhnimgjdctvfs\n" +
    "bqlporuexsszymhnimgjdctvfs\n" +
    "bqlporffxkwzyahnimgjditvfs\n" +
    "bqlporuexkwzyahnimcedctvbs\n" +
    "bqwpgruexkezyahnimgjdctvfs\n" +
    "bqldoruexkwzyahnimgjdcpvfu\n" +
    "bqlpoxueckwzyahnemgjdctvfs\n" +
    "bqlhoruqxkwzyahnimgjdctsfs\n" +
    "wqlporuexkwzychfimgjdctvfs\n" +
    "bqlporuenkwzyahnimvqdctvfs\n" +
    "aqlppruexkwzyahnimgjdcrvfs\n" +
    "bqlporuexzwzfahnimgjdcivfs\n" +
    "bqjporuexkwzyahnimgjdcqmfs\n" +
    "bqppkkuexkwzyahnimgjdctvfs\n" +
    "bqlporuervwzyahnimgldctvfs\n" +
    "bqoporxeykwzyahnimgjdctvfs\n" +
    "bqyporuehkwzyahnilgjdctvfs\n" +
    "bqlporuexkwzybvnimgjdctvfv\n" +
    "bqlporzehkwzyaznimgjdctvfs\n" +
    "bqiporuexkjzyahnimgjdatvfs\n" +
    "yqlpkruexkwzyahnimggdctvfs\n" +
    "brlporuexkwzyehnimgjdctvbs\n" +
    "bqlporuyxkwzyahnapgjdctvfs\n" +
    "bqlporuexkwzyaewimgjdttvfs\n" +
    "bqlporueskwzyahnimpjdcdvfs\n" +
    "bqlioruexkwzyahnimghdcbvfs\n" +
    "bqljoruexkwzyahtimgjdctmfs\n" +
    "bqlporgexkwzyaxnimgjvctvfs\n" +
    "bqlporuexkwxyahnimgodftvfs\n" +
    "mqlporupxkwzyahnimgjdcqvfs\n" +
    "bgkporuexkwzychnimgjdctvfs\n" +
    "jqlporuexgwzyawnimgjdctvfs\n" +
    "bqlperuebkwzyahniwgjdctvfs\n" +
    "bqlporuexkwzyahnbmgjdntvts\n" +
    "bqlporuexkwzyajnimgldctvfz\n" +
    "bqlpobuexkwzychnimgjdctvfu\n" +
    "bquporuexkwzyahiimgjdctvfp\n" +
    "bnlporbexkwzyahnimgjdctvfb\n" +
    "bqlporuexklzyahnimgtdctbfs\n" +
    "bqlworuexkwzyahnimkjdcpvfs\n" +
    "bqlporumxkwzyahnikejdctvfs\n" +
    "bqlporuexkwryahnimfjdctnfs\n" +
    "bqlioruenkwzywhnimgjdctvfs\n" +
    "bqlporulxbwzyahnimgjdctvfe\n" +
    "bqeporufxkwzqahnimgjdctvfs\n" +
    "bqlpbwuexkwzyahnimgjdctvfo\n" +
    "bqlpoduexkwzyahnimgvdctvrs\n" +
    "bqlporuexkwzlahnimgjdctvdw\n" +
    "bqlporuexkwzyahnimujdctdfp\n" +
    "iqlporuexvwvyahnimgjdctvfs\n" +
    "bclporuexkwzyahnimgjdzovfs\n" +
    "bqlporuerktzyahnamgjdctvfs\n" +
    "bqlporuexkwziajnimgjdctvfe\n" +
    "bqlpnrkexkwoyahnimgjdctvfs\n" +
    "bqlporuexkwznacnimgjdctvks\n" +
    "bqlporuexkrzyrhnimgjdcuvfs\n" +
    "bqltoruexkwzyahnnmgjdcivfs\n" +
    "bqlporuexkwzuahnimdjdctmfs\n" +
    "bqlporubxkbzyahnimgjdctmfs\n" +
    "bqlplruexkwdyhhnimgjdctvfs\n" +
    "bylporuexknzyahnimgjdctmfs\n" +
    "bqlporuexkwzyahqitgjdctvas\n" +
    "bquperuexkwzyahnimgjdcdvfs\n" +
    "bqlporuexktzyahnisgjdctvls\n" +
    "bqlporuexkwfyacnimtjdctvfs\n" +
    "bqleoraexkwzyahnimgjoctvfs\n" +
    "bqlporuexkwlyahnimrjdctvas\n" +
    "bqlphruexkwzyadnimujdctvfs\n" +
    "oqadoruexkwzyahnimgjdctvfs\n" +
    "belpzruexkwzyahnimgjjctvfs\n" +
    "bqlporuexkwzkahtbmgjdctvfs\n" +
    "bqlporulctwzyahnimgjdctvfs\n" +
    "bklptrwexkwzyahnimgjdctvfs\n" +
    "bqlpoqhexkwzjahnimgjdctvfs\n" +
    "tqlporjexkwzyahnimgjdctvfx\n" +
    "bqipwruexkwzyahnimgjdctvfd\n" +
    "bqlparueeawzyahnimgjdctvfs\n" +
    "bqlsoruexkrzyahnqmgjdctvfs\n" +
    "bqlsoruexhwzwahnimgjdctvfs\n" +
    "bquporuexkwsyihnimgjdctvfs\n" +
    "bwlporuexkwzyahwimgjdcuvfs\n" +
    "bqgpobuexkczyahnimgjdctvfs\n" +
    "bqlporuexkwzyahntmgjdspvfs\n" +
    "bqlporuetkwzjavnimgjdctvfs\n" +
    "bqlpoluwxkwzyahnimgpdctvfs\n" +
    "bqlporueykwzuahnimgjuctvfs\n" +
    "bqqporuexkwzyranimgjdctvfs\n" +
    "bjlporuexkwzyahnjmgjdctvts\n" +
    "bjlpofuenkwzyahnimgjdctvfs\n" +
    "bqhporuexbwzyahnfmgjdctvfs\n" +
    "bqlpofulxkwzyfhnimgjdctvfs\n" +
    "bqlporuexrwzyahuimgjdcwvfs\n" +
    "bblporaexkwzyahnicgjdctvfs\n" +
    "uqlpoxuexkwzuahnimgjdctvfs\n" +
    "bqlporuexkwzylhnimgjjhtvfs\n" +
    "bqlloruexkhiyahnimgjdctvfs\n" +
    "bqlpopuexkwzyahnymojdctvfs\n" +
    "bqlporuexkwgyyhnimgjdstvfs\n" +
    "bqlroruexxwzyahnumgjdctvfs\n" +
    "balpopuexkwzeahnimgjdctvfs\n" +
    "bqlporuexkwzyahniogjdqtvfc\n" +
    "bqlpoiuexkwgynhnimgjdctvfs\n" +
    "bqlpoyueukwzyahnimgjdcwvfs\n" +
    "bqtporuexkwtyahnimgjdctvfl\n" +
    "bqlporzexkwzyahnsmgjdctxfs\n" +
    "bqlporukxkwhyahnimgddctvfs\n" +
    "bklporuevowzyahnimgjdctvfs\n" +
    "bqgporuexmwzyahnimgjdctsfs\n" +
    "bqlporuetkxzyahnimgjoctvfs\n" +
    "bqlpsrzexkwzyahnimcjdctvfs\n" +
    "bqlporuexkwzzahaimgkdctvfs\n" +
    "bqlporuexkwzyahnimgjdmtvwd\n" +
    "bqlporuexkwzywhlimgjhctvfs\n" +
    "bqlporuexkwuhahnimgjdctvns\n" +
    "bqqporuexkizyahnimgjdctcfs\n" +
    "bqlvoruepkbzyahnimgjdctvfs\n" +
    "bqlporuexkwqyahnimgjfctvbs\n" +
    "bqlporuexkwzyahlimghuctvfs\n" +
    "bqlporuexkwzyahnizgjictvfb\n" +
    "bqlporuvxkjzyahaimgjdctvfs\n" +
    "bqljoruexkwzyahnizgjdctqfs\n" +
    "bqlporuexkwyyahnimgjdztvfv\n" +
    "jqlporqexkwzyahvimgjdctvfs\n" +
    "bqlporueakwzyabnimgjdctxfs\n" +
    "bqlporuezewzyahnimgfdctvfs\n" +
    "bqlporuzxklzyahnwmgjdctvfs\n" +
    "zqlpproexkwzyahnimgjdctvfs\n" +
    "bqlporuefkwzyahnlmgjdgtvfs\n" +
    "bqlporoenkwzyahnkmgjdctvfs\n" +
    "bqwporuexkwzyahnimcjdctvfk\n" +
    "bqlporuexkwbyahaimgjdctvus\n" +
    "bqlporujxkwzyahnimgjfntvfs\n" +
    "bqlooruexkvzyahnimjjdctvfs\n" +
    "bqlpomuexowzyahnimgjcctvfs\n" +
    "bqlpoquexkwzvahnimgjdctvfl\n" +
    "bclpopuexowzyahnimgjdctvfs\n" +
    "bqlporuexcwzyahnimgjdctlfb\n" +
    "bqlporgexkwzyalnimgjdctvfq\n" +
    "bqppiruexkwzyyhnimgjdctvfs\n" +
    "bqlporaexkwnmahnimgjdctvfs\n" +
    "bqhporuexkwzyahlomgjdctvfs\n" +
    "bqlloruexkwzuahnimgjdctvfb\n" +
    "bqhporuexkwzyahnemgjdcovfs\n" +
    "bqlpiruexkwdyahwimgjdctvfs\n" +
    "bqlporuexkwryahnimgjtdtvfs\n" +
    "bqeporuexkwzyahgixgjdctvfs\n" +
    "bqlporuexkwyqahnimgfdctvfs\n" +
    "bqlporuexkwzyaoniggydctvfs\n" +
    "bqlpouuexkazyahnimgxdctvfs\n" +
    "brlporuexkwzyahvimgjdctvps\n" +
    "bqlforuexkwzyrhnitgjdctvfs\n" +
    "bqlpiruexkwzyfhnjmgjdctvfs\n" +
    "bqlpoebexkwzyxhnimgjdctvfs\n" +
    "bblporoezkwzyahnimgjdctvfs\n" +
    "bglporuexkwzyajqimgjdctvfs\n" +
    "bqlpxcuixkwzyahnimgjdctvfs\n" +
    "bqlporuaekwzyahniegjdctvfs\n" +
    "hqvporuexkwzyahnimgjectvfs\n" +
    "qllporuexkwzyahnimgjdctvhs\n" +
    "bqlporaexkpzyahnlmgjdctvfs\n" +
    "bqlporuexkwzyabnzmgjqctvfs\n" +
    "bqlporuexbvzyahnimgjdctrfs\n" +
    "bqdzoruetkwzyahnimgjdctvfs\n" +
    "bslporuexkwzyahnimgjdctdos\n" +
    "bqlporfexkwzylwnimgjdctvfs\n" +
    "bqrporueykwzyavnimgjdctvfs\n" +
    "bqlporuexkweythnomgjdctvfs\n" +
    "bqlpozuepkwzyahnimgjdctdfs\n" +
    "bqoporuexqhzyahnimgjdctvfs\n" +
    "bqlporucxkwzyahnimtjdctifs\n" +
    "bqlpobuexawzyahnimgjdcthfs\n" +
    "dklporuexkwzyahnimhjdctvfs\n" +
    "bclpkquexkwzyahnimgjdctvfs\n" +
    "bqlporuexkwzyafnfmljdctvfs\n" +
    "bqlporuexkwzympnimgjsctvfs\n" +
    "bqlporuexkwzyaonimdjactvfs\n" +
    "bqlporuvxkwzywhnimgjdctvks\n" +
    "bqlporuexkwzgahnimbjdctvfn\n" +
    "bqlqoruexvwzqahnimgjdctvfs\n" +
    "bqlporuexkmkyahniggjdctvfs\n" +
    "bqlneruexkwzyjhnimgjdctvfs\n" +
    "bqlporueqkwzyahnbmgjdctvfl\n" +
    "bqlpgruexkwzyahnimjvdctvfs\n" +
    "nqlpsruevkwzyahnimgjdctvfs\n" +
    "bqhpouuexkwzyahnmmgjdctvfs\n" +
    "bqnporuexkwzyahnimojdctqfs\n" +
    "bqlpordexkwztahnimgjdctvds\n" +
    "eqlporufxkwzyahniigjdctvfs\n" +
    "balporuebkwzyahnimgjdctvfv\n" +
    "bqlprruexrwzwahnimgjdctvfs\n" +
    "bqlporuepkwxyahnimggdctvfs\n" +
    "bqlporfexkwzyahnqjgjdctvfs\n" +
    "bqaporuexvwzyahnimgjdctvfy\n" +
    "bqlporuexkwzyawnibgjdctmfs\n" +
    "eqlhoruexkwzyahiimgjdctvfs\n" +
    "bqlporuexkbzyahnimgsdhtvfs\n" +
    "bqlporhexkfzyahnimgjdcgvfs\n" +
    "bqeporuexkxzyahnimgjdcavfs\n" +
    "bqlporoerkwzyahnimgjdctnfs\n" +
    "bqlporuemkwzyshnimgjdatvfs\n" +
    "bilporuexkwyyahnimgvdctvfs\n" +
    "xqlporuexkwzyahnnmgjdctvfl\n" +
    "bqlborumxkwzsahnimgjdctvfs\n" +
    "bqlporsexcwzvahnimgjdctvfs\n" +
    "bqlporxexkwzyapnimgbdctvfs\n" +
    "bqlpmruexkwzyahnimgbdcpvfs\n" +
    "qqlroruexkwzyahnihgjdctvfs\n" +
    "bqnporuexkbzyaknimgjdctvfs\n" +
    "bqxpoeuexcwzyahnimgjdctvfs\n" +
    "bqlporuexkqzyahnidgjdcivfs\n" +
    "zqkmoruexkwzyahnimgjdctvfs\n" +
    "bqlporuexkwzyahzimgjqjtvfs\n" +
    "bqfporuenkwzyahiimgjdctvfs\n" +
    "bqlporuexkwzyahuimszdctvfs\n" +
    "bklporurmkwzyahnimgjdctvfs\n" +
    "bqlpotuexktzyahnimgjdcfvfs\n" +
    "bqlporuexkwxyahnimgxdltvfs\n" +
    "bqmporuexkwzoahnimgjdctvys\n" +
    "bqlporuexvwzyahnimgjdnnvfs\n" +
    "bqzporuexkwzyahnkmgjdctsfs\n" +
    "bqmporuexkwzyahnihgjdctvfq\n" +
    "bqlporuexkwzyavnimgjdcrvos\n" +
    "bklpopuexkwzyahnimgjdctvfb\n" +
    "bvlcoruexkwzyapnimgjdctvfs\n" +
    "bqlboruexzwcyahnimgjdctvfs\n" +
    "bqlporuexdwzyihnimgydctvfs\n" +
    "bqlpovuexkwzyaynimgjdctvfq\n" +
    "bqlarruebkwzyahnimgjdctvfs\n" +
    "fqlporuexkwzfahnimgjdctsfs\n" +
    "bqlporuexowzyahnjmgjdctdfs\n" +
    "bqlporuexkwzyahnrmkjdctyfs";

module.exports = input.split("\n");